package org.grails.quiz

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import groovy.transform.ToString

/**
 * Created by rvanderwerf on 5/19/17.
 */

@DynamoDBTable(tableName="StarTrekQuiz")
@ToString(includeNames=true, includeFields=true)
class QuizItem {

    public static final Long DEFAULT_HASH_KEY = 123
    @DynamoDBHashKey
    Long questionId  = DEFAULT_HASH_KEY // Hash key default

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    String id // Range key, with an automatically generated ID

    @DynamoDBAttribute(attributeName = "Question")
    String question

    @DynamoDBAttribute
    Integer answer

    @DynamoDBAttribute
    String option1

    @DynamoDBAttribute
    String option2

    @DynamoDBAttribute
    String option3

    @DynamoDBAttribute
    String option4

}
